name: Deploy Web Portal to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'web-portal/**' # Trigger only when files in the web-portal folder change

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web-portal' # Deploy only the contents of the web-portal subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
